server_connect_timeout: 5000
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - hub
  - spawn
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 20
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 37057a79-f05f-481a-9d11-f3b967528870
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  hub:
    motd: '&1Hub'
    address: localhost:25577
    restricted: false
  spawn:
    motd: '&1Spawn'
    address: localhost:25588
    restricted: false
